import type { Metadata } from "next";
import "./globals.css";

const siteUrl = "https://francogregorio.com";

export const metadata: Metadata = {
  title: "Franco Gregorio",
  description: "Generated by Franco Gregorio",
  metadataBase: new URL(siteUrl),
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              html, body {
                margin: 0;
                min-height: 100%;
                background-color: inherit;
              }
              html {
                background: #ffffff;
              }
              body:has(#initial-loader) {
                overflow: hidden;
              }
              #initial-loader {
                position: fixed;
                inset: 0;
                z-index: 9999;
                display: flex;
                align-items: center;
                justify-content: center;
                background: inherit;
              }
              #initial-loader .initial-loader-spinner {
                width: 2rem;
                height: 2rem;
                border-radius: 9999px;
                border: 1.5px solid #e5e5e5;
                border-top-color: #252525;
                animation: initialLoaderSpin 0.7s linear infinite;
              }
              @keyframes initialLoaderSpin {
                to { transform: rotate(360deg); }
              }
            `,
          }}
        />
      </head>
      <body suppressHydrationWarning className="bg-background">
        <div id="initial-loader" aria-hidden="true">
          <div className="initial-loader-spinner" />
        </div>
        {children}
      </body>
    </html>
  );
}
