import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const siteUrl = "https://francogregorio.com";

export const metadata: Metadata = {
  title: "Franco Gregorio",
  description: "Generated by Franco Gregorio",
  metadataBase: new URL(siteUrl),
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              html, body {
                margin: 0;
                min-height: 100%;
                background-color: inherit;
              }
              html {
                background: oklch(0.95 0.02 145);
              }
              html.dark {
                background: oklch(0.18 0.02 150);
              }
              html:has(#initial-loader) {
                background-color: oklch(0.95 0.02 145);
              }
              html.dark:has(#initial-loader) {
                background-color: oklch(0.18 0.02 150);
              }
              body:has(#initial-loader) {
                overflow: hidden;
              }
              #initial-loader {
                position: fixed;
                inset: 0;
                z-index: 9999;
                display: flex;
                align-items: center;
                justify-content: center;
                background-color: oklch(0.95 0.02 145);
              }
              html.dark #initial-loader {
                background-color: oklch(0.18 0.02 150);
              }
              #initial-loader .initial-loader-spinner {
                width: 2rem;
                height: 2rem;
                border-radius: 9999px;
                border: 1.5px solid oklch(0.84 0.03 150);
                border-top-color: oklch(0.42 0.1 152);
                animation: initialLoaderSpin 0.7s linear infinite;
              }
              html.dark #initial-loader .initial-loader-spinner {
                border-color: oklch(0.32 0.03 150);
                border-top-color: oklch(0.72 0.1 152);
              }
              @keyframes initialLoaderSpin {
                to { transform: rotate(360deg); }
              }
            `,
          }}
        />
      </head>
      <body suppressHydrationWarning className="bg-background">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <div id="initial-loader" aria-hidden="true">
            <div className="initial-loader-spinner" />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
